// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRXEEWzUI9qPL7uFrblJm2Nbr4blNqY5Q',
    appId: '1:995323281278:web:742ab733bd0d2778227d2f',
    messagingSenderId: '995323281278',
    projectId: 'elder-home-app',
    authDomain: 'elder-home-app.firebaseapp.com',
    storageBucket: 'elder-home-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQXJxE6sTJrzd71zirqr-Sy9p76VVEfYc',
    appId: '1:995323281278:android:c289e6646eea9646227d2f',
    messagingSenderId: '995323281278',
    projectId: 'elder-home-app',
    storageBucket: 'elder-home-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCk-htzHddJUGSN-KcXgs_weXGYhd-hhaA',
    appId: '1:995323281278:ios:aadb0436a0fb180f227d2f',
    messagingSenderId: '995323281278',
    projectId: 'elder-home-app',
    storageBucket: 'elder-home-app.firebasestorage.app',
    iosBundleId: 'com.example.elderlyHelper',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCk-htzHddJUGSN-KcXgs_weXGYhd-hhaA',
    appId: '1:995323281278:ios:aadb0436a0fb180f227d2f',
    messagingSenderId: '995323281278',
    projectId: 'elder-home-app',
    storageBucket: 'elder-home-app.firebasestorage.app',
    iosBundleId: 'com.example.elderlyHelper',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBRXEEWzUI9qPL7uFrblJm2Nbr4blNqY5Q',
    appId: '1:995323281278:web:ead2e542e0274ad7227d2f',
    messagingSenderId: '995323281278',
    projectId: 'elder-home-app',
    authDomain: 'elder-home-app.firebaseapp.com',
    storageBucket: 'elder-home-app.firebasestorage.app',
  );
}
